<a href="https://colab.research.google.com/github/wwwlovecom/my_rep/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [ ]:
import numpy as np

array1 = np.arange(1, 21)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [ ]:
matrix2 = np.ones((4, 4))
print(matrix2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [ ]:
array3 = np.random.uniform(-1, 1, (5, 5))
print(array3)

[[ 0.71882512  0.79315316  0.86907349  0.47051927 -0.6198181 ]
 [-0.50281996 -0.56923541 -0.80260404  0.74538994 -0.60687343]
 [-0.28216092  0.76082794 -0.582468    0.65225839  0.15863751]
 [ 0.19562466 -0.55446835 -0.35224999  0.18816082  0.6121251 ]
 [-0.15332635  0.59647867  0.50259107  0.2726243  -0.92668215]]


4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
array4 = np.random.rand(3, 3)
print(array4)

[[0.10851733 0.46743587 0.10654309]
 [0.83492219 0.34506576 0.19671356]
 [0.22815102 0.22888758 0.24788789]]


5. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a5 = np.random.randint(1, 21, size=6)
b5 = np.random.randint(1, 21, size=6)

suma5 = a5 + b5
riz5 = a5 - b5
mnoz5 = a5 * b5

print("Масив a:", a5)
print("Масив b:", b5)
print("Сума:", suma5)
print("Різниця:", riz5)
print("Множення:", mnoz5)

Масив a: [ 8 10 15  1 10 19]
Масив b: [13  2  4 12 10 10]
Сума: [21 12 19 13 20 29]
Різниця: [ -5   8  11 -11   0   9]
Множення: [104  20  60  12 100 190]


6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [ ]:
A6 = np.random.randint(1, 6, size=(3, 2))
B6 = np.random.randint(1, 6, size=(2, 4))

mnoz6 = np.dot(A6, B6)

print("Матриця A (3x2):")
print(A6)
print("\nМатриця B (2x4):")
print(B6)
print("\nРезультат множення:")
print(mnoz6)

Матриця A (3x2):
[[2 1]
 [2 2]
 [2 4]]

Матриця B (2x4):
[[5 4 3 1]
 [1 3 4 2]]

Результат множення:
[[11 11 10  4]
 [12 14 14  6]
 [14 20 22 10]]


7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix7 = np.random.rand(3, 3)

transp = matrix7.T

print("Оригінальна матриця:")
print(matrix7)

print("\nТранспонована матриця:")
print(transp)

Оригінальна матриця:
[[0.34140325 0.90312698 0.64244765]
 [0.60498046 0.24035893 0.90243525]
 [0.04032403 0.26667812 0.25571097]]

Транспонована матриця:
[[0.34140325 0.60498046 0.04032403]
 [0.90312698 0.24035893 0.26667812]
 [0.64244765 0.90243525 0.25571097]]


8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
A8 = np.random.randint(1, 11, size=(3, 3))
B8 = np.random.randint(1, 11, size=(3, 3))

riz8 = A8 - B8

print("Матриця A:")
print(A8)

print("\nМатриця B:")
print(B8)

print("\nРізниця:")
print(riz8)

Матриця A:
[[ 3  4  6]
 [ 6 10  8]
 [ 1  5  1]]

Матриця B:
[[ 8  1 10]
 [ 4  8  6]
 [ 3  9 10]]

Різниця:
[[-5  3 -4]
 [ 2  2  2]
 [-2 -4 -9]]


9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [ ]:
A9 = np.random.randint(-5, 6, size=(3, 3))
B9 = np.random.randint(-5, 6, size=(3, 3))

mnoz9 = np.dot(A9, B9)

print("Матриця A:")
print(A9)

print("\nМатриця B:")
print(B9)

print("\nДобуток:")
print(mnoz9)

Матриця A:
[[ 1  4 -2]
 [-5 -5  5]
 [-1  1  0]]

Матриця B:
[[ 0 -2 -2]
 [-5  0  4]
 [ 3  5  3]]

Добуток:
[[-26 -12   8]
 [ 40  35   5]
 [ -5   2   6]]


10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
matrix10 = np.random.uniform(-1, 1, size=(3, 3))

suma10 = np.sum(matrix10, axis=1).reshape(-1, 1)

print("Матриця:")
print(matrix10)

print("\nСума рядків:")
print(suma10)

Матриця:
[[-0.08229254  0.88862098 -0.76043766]
 [-0.00809137 -0.67246692  0.58668584]
 [-0.87448592  0.12177198  0.88492726]]

Сума рядків:
[[ 0.04589078]
 [-0.09387245]
 [ 0.13221332]]


Посилання на gitHub: https://github.com/wwwlovecom/my_rep