<a href="https://colab.research.google.com/github/wwwlovecom/my_rep/blob/main/%D0%9B%D0%A01_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D0%A7%D0%B0%D1%81%D1%82%D0%B8%D0%BD%D0%B0_1%2C_%D0%9E%D0%BB%D1%96%D0%B9%D0%BD%D0%B8%D0%BA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'2.0.2'

1. Створити матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [6]:
matrix = np.random.randint(1, 6, size =(3,3))

matrix

array([[2, 4, 5],
       [2, 5, 3],
       [3, 5, 2]])

2. Обчислити визначник матриці

In [7]:
det = np.linalg.det(matrix)
det

np.float64(-15.000000000000007)

3. Знайти добуток всіх елементів матриці

In [8]:
product = np.prod(matrix)
product

np.int64(36000)

In [9]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(36000)

4. Знайти суму всіх елементів матриці

In [10]:
sum = np.sum(matrix)
sum

np.int64(31)

5. Обчислити найбільший, найменший елементи

In [12]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)

min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 2


6. Знайти середнє значення елементів матриці

In [13]:
mean = np.mean(matrix)
print("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 3.4444444444444446


7. Знайти матрицю, що складена з квадратних коренів

In [14]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.41421356 2.         2.23606798]
 [1.41421356 2.23606798 1.73205081]
 [1.73205081 2.23606798 1.41421356]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [17]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)
#В результаті отримали вектор-стовпчик

Сума елементів кожного рядка:
[[11]
 [10]
 [10]]


9. Створити вектор, що вмістить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням

In [16]:
vector = np.random.randint(0, 10, size = 25)

print("Початковий вектор:")
print(vector)

#Сортуємо числа за спаданням
sorted_vector = np.sort(vector)[::-1]

print("Вектор після сортування за спаданням:")
print(sorted_vector)

Початковий вектор:
[6 4 2 3 5 6 5 7 5 9 8 9 0 7 0 8 4 3 1 0 0 7 2 1 7]
Вектор після сортування за спаданням:
[9 9 8 8 7 7 7 7 6 6 5 5 5 4 4 3 3 2 2 1 1 0 0 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [18]:
from scipy import stats

#Знаходимо моду
mode = stats.mode(vector)

#Знаходимо медіану
median = np.median(vector)

#Знаходимо середнє
mean = np.mean(vector)

#Знаходимо максимальне значення
max_value = np.max(vector)

#Знаходимо мінімальне значення
min_value = np.min(vector)

print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(0), count=np.int64(4))
Медіана: 5.0
Середнє: 4.36
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповлені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку

In [19]:
#Створюємо дві матриці 4х4 із випадкових цілих чисел від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[ 4  2  9  7]
 [ 1  8 10  7]
 [10  3  5  9]
 [ 8  7  1  3]]

Матриця 2:
[[ 6 10  4  4]
 [ 8  9  2  5]
 [ 7  3  3 10]
 [ 3  6  1  4]]


In [22]:
#Обчислуємо суму матриць
matrix_sum = matrix1 + matrix2

#Обчислюємо різницю матриць
matrix_diff = matrix1 - matrix2

#Обчислюємо поелементний добуток матриць
matrix_product = matrix1 * matrix2

#Обчислюємо поелементну частку матриць
#Для запобігання ділення на нуль, використовуємо np.divide з параметром where
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))

print("Сума матриць:")
print(matrix_sum)

print("\nРізниця матриць:")
print(matrix_diff)

print("\nПоелементний добуток матриць:")
print(matrix_product)

Сума матриць:
[[10 12 13 11]
 [ 9 17 12 12]
 [17  6  8 19]
 [11 13  2  7]]

Різниця матриць:
[[-2 -8  5  3]
 [-7 -1  8  2]
 [ 3  0  2 -1]
 [ 5  1  0 -1]]

Поелементний добуток матриць:
[[24 20 36 28]
 [ 8 72 20 35]
 [70  9 15 90]
 [24 42  1 12]]


12. Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що містить числа 0.0-2.0

In [23]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [24]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [26]:
x2 = np.arange(3.0)
x2

array([0., 1., 2.])

In [27]:
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])